---
- name: Install dependencies
  apt:
    pkg:
      - git
      - curl
      - build-essential
      - libssl-dev
    update_cache: yes
    cache_valid_time: 3600
  tags: nvm

- name: Install nvm
  become: yes
  become_user: "{{ nvm.user }}"
  git: repo=https://github.com/creationix/nvm.git dest=~/.nvm version={{ nvm.version }}
  tags: nvm

- name: Source nvm in ~/.profile
  become: yes
  become_user: "{{ nvm.user }}"
  lineinfile: >
    dest=~/.profile
    line="source ~/.nvm/nvm.sh"
    create=yes
  tags: nvm

- name: Install {{ nvm.node_version }}
  become: yes
  become_user: "{{ nvm.user }}"
  shell: bash -lc "nvm install {{ nvm.node_version }}"
  register: nvm_install_result
  changed_when: "'is already installed.' not in nvm_install_result.stderr"
  tags: nvm

- name: Check if {{ nvm.node_version }} is the default node version
  become: yes
  become_user: "{{ nvm.user }}"
  shell: bash -lc "nvm alias default"
  register: nvm_check_default
  changed_when: False
  tags: nvm

- name: Set default node version to {{ nvm.node_version }}
  become: yes
  become_user: "{{ nvm.user }}"
  shell: bash -lc "nvm alias default {{ nvm.node_version }}"
  when: nvm.node_version not in nvm_check_default.stdout
  tags: nvm
